### ISSUE TITLE
Upstream / Origin

### ISSUE THREAD

**Issue by vonloxley** [markiewb/nb-git-toolbar#4]
The pull / push from upstream-buttons work on the default repository, which is called `origin` per default. wouldn’t it be better to let the tooltips reflect this and call then push / pull from origin?

**Comment by markiewb** [comment]
@vonloxley: Origin is not the default. You can have multiple origins. For example to pull from repo x, but push to repo y. 

I leave it that way. This plugin only provides a prepared toolbar, which you could have configured yourself within the IDE. The label comes from the build-in NB actions

**Comment by vonloxley** [comment]
No problem, but please note, that you can have multiple `remotes`, of which the default one, per [convention](https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes), is called `origin`.
