### ISSUE TITLE
Enhancement: Let the user select the current branch from a dropdown or show it.

### ISSUE THREAD

**Issue by EdwinFLopez** [markiewb/nb-git-toolbar#5]
Hi and thanks for your work.
I'm wondering if it is possible to add a dropdown box (or a label in its defect) to let the user select the current branch or at least a label to show the current branch, similar to what InteliJ Idea does.
Thank you.

**Comment by markiewb** [comment]
It already exists. Double click on the label to open the "switch branch"
dialog!

With kind regards, markiewb

2016-12-07 15:56 GMT+01:00 Edwin F. López A. <notifications@github.com>:

**Comment by EdwinFLopez** [comment]
Thanks for answering.
Maybe I didn't express myself clearly. I'm aware of the "switch to branch" button, it works nicely, what I meant by this is a way to see at anytime in what branch I'm working on. So, what I imagine is like an extra label at the end of the buttons that shows "origin/branch-XXXXXX". So far, we have the create and switch buttons.

**Comment by markiewb** [comment]
Use the other plugin https://github.com/markiewb/nb-git-branch-in-statusbar
or use the label decorators via View->Show Versioning Labels

Den 7 dec. 2016 18:05 skrev "Edwin F. López A." <notifications@github.com>:

**Comment by EdwinFLopez** [comment]
Awesome, thanks. I'm closing this then.
