### ISSUE TITLE
Git Toolbar not working with remote C/C++ project

### ISSUE THREAD

**Issue by ggqc007** [markiewb/nb-git-toolbar#6]
Is this a known issue? Netbeans added git support for remote C/C++ projects. The tool bar does not seems to work with that new feature.

Any chance for a fix?? 

Ty much!

**Comment by markiewb** [comment]
I never used NB for C/C++ development. This plugin is only a preset toolbar of existing actions.

I am not sure if there exist other git actions specially for git remote projects. Try it yourself. Perhaps other existing git actions work. 
* Right click on the empty space of toolbar -> Customize...
* Drag the Git-Actions to the toolbar

These actions are context aware. If you select a file within a git repo, then the actions are enabled. If you find some working action, then a preset toolbar could be created and provided as a plugin.

**Comment by ggqc007** [comment]
Hello! Thanx for your reply. 

Yes the options are there. The thing is now called "GitRemote" wich is just below the "Git" section your addon is based on.

Any hope you find the time for this? ;o)  

I did not look at the code but i might give a look at it when i get a sec if you dont have the time and, of course, if you dont mind..

**Comment by ggqc007** [comment]
Hello again,

I added the GitRemote toolbar to your plugin. Want me to push the updated version?

**Comment by markiewb** [comment]
I created a fork of the plugin. https://github.com/markiewb/nb-gitremote-toolbar
Your code is integrated there. Thank you!

**Comment by ggqc007** [comment]
Hello again,

I would like to maintain the GitRemote version now that i have learned the
Netbeans layer thing if you dont mind. I am a heavy remote C/C++
development user. I can improve or fix it when/if it get broken.

Thank you!

Guillaume



2017-06-10 16:27 GMT-04:00 markiewb <notifications@github.com>:
